<?php // FILE: templates/_catalog_filters.php ?>
<form id="filter-form" method="GET" action="catalog.php">
    <div class="space-y-4 md:space-y-0 md:grid md:grid-cols-2 lg:grid-cols-5 md:gap-4">
        <div class="lg:col-span-2"><label for="search" class="sr-only">Search</label><input type="text" name="search" id="search" value="<?= e($search_term) ?>" placeholder="Search by name or manufacturer..." class="w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500"></div>
        <div><label for="availability" class="sr-only">Availability</label><select name="availability" id="availability" class="w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500"><option value="all" <?= ($filter_availability == 'all') ? 'selected' : '' ?>>All Availability</option><option value="in_stock" <?= ($filter_availability == 'in_stock') ? 'selected' : '' ?>>In Stock</option><option value="out_of_stock" <?= ($filter_availability == 'out_of_stock') ? 'selected' : '' ?>>Out of Stock</option></select></div>
        <div><label for="category" class="sr-only">Category</label><select name="category" id="category" class="w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500"><option value="">All Categories</option><?php foreach ($categories as $cat): ?><option value="<?= e($cat) ?>" <?= ($filter_category == $cat) ? 'selected' : '' ?>><?= e($cat) ?></option><?php endforeach; ?></select></div>
        <div><label for="sort" class="sr-only">Sort By</label><select name="sort" id="sort" class="w-full rounded-md border-gray-300 shadow-sm focus:border-teal-500 focus:ring-teal-500"><option value="name_asc" <?= ($sort_order == 'name_asc') ? 'selected' : '' ?>>Sort: Name (A-Z)</option><option value="name_desc" <?= ($sort_order == 'name_desc') ? 'selected' : '' ?>>Sort: Name (Z-A)</option><option value="price_asc" <?= ($sort_order == 'price_asc') ? 'selected' : '' ?>>Sort: Price (Low-High)</option><option value="price_desc" <?= ($sort_order == 'price_desc') ? 'selected' : '' ?>>Sort: Price (High-Low)</option></select></div>
    </div>
     <div class="mt-6 flex flex-col md:flex-row justify-between items-center gap-4">
        <a href="catalog.php" class="w-full md:w-auto text-center text-sm text-gray-600 hover:text-teal-600">Reset All Filters</a>
        <button type="submit" class="w-full md:w-auto btn-primary py-2 px-6">Apply Filters</button>
     </div>
</form>